<section>
    <iframe
        width="560"
        height="315"
        src="https://www.youtube.com/watch?v=GlOETXrU-wQ"
        frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
    ></iframe>
    <script
        src="https://vwrap.cielo24.com/vwrap.js"
        data-share-enabled="true"
        data-provider="youtube"
        data-print-enabled="true"
        data-video-id="WAbMnu55lys"
        data-job-id="76bace73fb844a82bf5d04065abe8378"
        data-download-enabled="true"
        data-mdps-version="3"
    ></script>
</section>
